### ISSUE TITLE
InvalidArgumentException : 340282366920938463463374607431768211455 range out U128

### ISSUE THREAD

**Issue by leonardocustodio** [gmajor-encrypt/php-scale-codec#15]
Hello @gmajor-encrypt ,

We are also getting an error when trying to encode the maximum value possible for a u128.
It is possible to encode until `340282366920938463463374607431768211454` that would be `feffffffffffffffffffffffffffffff`
But when trying to encode `340282366920938463463374607431768211455` that would be `ffffffffffffffffffffffffffffffff`
We get "range out u128". Here is a test to reproduce it:

```
$codec = $codec->createTypeByTypeString("u128");
$this->assertEquals("ffffffffffffffffffffffffffffffff", $codec->encode("340282366920938463463374607431768211455"));
```

**Comment by gmajor-encrypt** [comment]
https://github.com/gmajor-encrypt/php-scale-codec/pull/17
