### ISSUE TITLE
InvalidArgumentException : Unknown codec type " u32"

### ISSUE THREAD

**Issue by leonardocustodio** [gmajor-encrypt/php-scale-codec#16]
Hello @gmajor-encrypt ,

There is a bug in BTreeMap that we cannot put a space between the types like so: `BTreeMap<String, u32>`
We allow space in tuples like `(u8, u8)` and also in Results like `Result<u8, bool>` to make consistent we should also allow space in BTreeMap.

You can test the issue with the following:
```
        $codec = new ScaleInstance(Base::create());
        $this->assertEquals(["bazzing" => 69], $codec->process("BTreeMap<String, u32>", new ScaleBytes("0x041c62617a7a696e6745000000")));
        $this->assertEquals("041c62617a7a696e6745000000", $codec->createTypeByTypeString("BTreeMap<String, u32>")->encode(["bazzing" => 69]));
        $this->expectExceptionMessage("sub_type invalid");
        $codec->createTypeByTypeString("BTreeMap<String>")->encode(["a" => 3]);
```

**Comment by gmajor-encrypt** [comment]
This issue has been fixed, thank you feedback https://github.com/gmajor-encrypt/php-scale-codec/pull/17
