### ISSUE TITLE
`Option<Option<T>>` not capable to be encoded/decoded

### ISSUE THREAD

**Issue by leonardocustodio** [gmajor-encrypt/php-scale-codec#21]
Just opening a new issue on this so we can track it:

Awesome, `Option<bool>` seems to be working fine now. Thanks a lot. But we still have an issue with `Option<Option<T>>`
Consider this custom type for example:

```
{
  "MutateToken": {
    "collectionId": "Compact<u128>",
    "tokenId": "Compact<u128>",
    "mutation": "TokenMutation"
  },
  "TokenMutation": {
    "behavior": "Option<Option<TokenMarketBehavior>>",
    "listingForbidden": "Option<bool>"
  },
  "TokenMarketBehavior": {
    "_enum": {
      "IsCurrency": "Null"
    }
  }
}
```

If we try to encode this:
```
collectionId = 57005
tokenId = 255
behavior = null
listingForbidden = null
```
We get the expected result:
`b67a0300fd030000`

If we try to encode:
```
collectionId = 57005
tokenId = 255
behavior = null
listingForbidden = true
```
We get the expected result:
`b67a0300fd03000101`

If we try to encode:
```
collectionId = 57005
tokenId = 255
behavior = IsCurrency
```
We get the expected result:
`b67a0300fd0301010100`

But there is no way to encode
`behavior = Some(None)`

Also, if we try to decode the following:
`b67a030000` => That would be behavior `None`
`b67a03010000` => That would be behavior `Some(None)`

We get the same output:
```
  "collectionId" => "57005"
  "tokenId" => "255"
  "mutation" => array:2 [
    "behavior" => null
    "listingForbidden" => null
  ]
```

_Originally posted by @leonardocustodio in https://github.com/gmajor-encrypt/php-scale-codec/issues/19#issuecomment-1301536328_

**Comment by gmajor-encrypt** [comment]
@leonardocustodio This is indeed a difficult problem to deal with, Not very easy to distinguish between Some(NULL) and Null

**Comment by leonardocustodio** [comment]
I've reported the same issue to Subsquid what was decided in there was to transform the `Option` to an `enum` (it is an enum on rust anyway) instead of decoding it to the final value. So for `Option<T>`
Instead of returning `null` to `None` and `T` to `Some<T>`
They are now returning the enum named `None` with `null` value or the enum named `Some` with the `T` as value. This makes it possible to chain `Option<Option<T>>` here their commit as reference  https://github.com/subsquid/squid/commit/559e47242924946ab705c2891d8844631131d8bd

**Comment by gmajor-encrypt** [comment]
@leonardocustodio I add some fixes there https://github.com/gmajor-encrypt/php-scale-codec/blob/master/test/Codec/Test/TypeTest.php#L216, I don't know if this will affect your use
