### ISSUE TITLE
Uncaught UnexpectedValueException: InValid value \"20\" type bool in gmajor/substrate-codec-php/src/Codec/Types/ScaleInstance.php:230

### ISSUE THREAD

**Issue by leonardocustodio** [gmajor-encrypt/php-scale-codec#22]
I'm getting this issue when trying to decode some extrinsics. Here is the encoded data: 

`0x7d02840068b427dda4f3894613e113b570d5878f3eee981196133e308c0a82584cf2e16001bab3ed699808a8f2cae97b4545972b0125a7cdb65e183e4e00dfe0e5c7f9e55de2203d13520d4f14bf8b62dcf2a82e1a7215796f1873446b4203c1fd2a0cbd8083006d0c0028040068b427dda4f3894613e113b570d5878f3eee981196133e308c0a82584cf2e160bd2c001110041300008a5d784563010101140000`

And here the metadata: https://justpaste.it/39g0l

It is possible to decode the same extrinsic perfectly fine on polkadot-js
![image](https://user-images.githubusercontent.com/5619696/208555368-571574b1-f4b8-4998-8454-949c774a3569.png)

**Comment by leonardocustodio** [comment]
That PR has a Testcase that shows the issue.

**Comment by leonardocustodio** [comment]
It seems this error was caused by the new `Option<Option<T>>` support. I've downgraded the lib in my local environment to this commit https://github.com/gmajor-encrypt/php-scale-codec/commit/e1204860c9e1c24660dde6d031d7184a81be2155 and this error did not happen anymore on those transactions.

**Comment by gmajor-encrypt** [comment]
@leonardocustodio sorry for the late reply. I will fix it as soon as possible

**Comment by leonardocustodio** [comment]
No problem, thanks @gmajor-encrypt

**Comment by gmajor-encrypt** [comment]
@leonardocustodio hello, sorry for the late reply, this issue has been fixed. Please try again

**Comment by leonardocustodio** [comment]
Thank you @gmajor-encrypt , great work :)
