### ISSUE TITLE
Bug: Encoding "Raw: Bytes" is wrong

### ISSUE THREAD

**Issue by leonardocustodio** [gmajor-encrypt/php-scale-codec#27]
Scale codec uses particular encoding for Raw Bytes.

Right now it is impossible to encode this way in this library

https://github.com/polkascan/py-scale-codec/blob/f676638998ce612d9f0b38b135f77a95eacd51ce/scalecodec/types.py#L1334-L1415

**Comment by gmajor-encrypt** [comment]
@leonardocustodio I will take a look. Thanks report

**Comment by gmajor-encrypt** [comment]
@leonardocustodio Data type has been update. I can try https://github.com/gmajor-encrypt/php-scale-codec/pull/28/files

**Comment by leonardocustodio** [comment]
Seems to be working fine, thank you :)
